language: C++
sudo: false
addons:
  apt:
    packages: &baseline-packages
      - valgrind

# Template some configurations for different distros, to be used in the matrix
# below
_xenial-conf: &xenial
  dist: xenial
  addons:
    apt:
      packages:
        - *baseline-packages
        - libboost-test-dev

_xenial-clang-env-conf: &xenial-clang-env
  env:
    - CC=clang
    - CXX=clang++

_bionic-conf: &bionic
  dist: bionic
  addons:
    apt:
      packages:
        - *baseline-packages
        - libboost-test-dev
        - libboost-system-dev

matrix:
  include:
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=3.8.1  # default on Debian stretch - does NOT work yet
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=3.9.1
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=4.0.0
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=5.0.2
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=6.0.1
    - <<: *bionic
      env: LLVM_VERSION=7.1.0
    - <<: *bionic
      env: LLVM_VERSION=8.0.0

before_script:
  - git submodule init
  - git submodule update
  - ./travis/install_deps.sh
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH=$LLVM_DIR/lib
  - autoreconf --install
  - ./configure CXXFLAGS="-I"`pwd`"/deps/immer/" || (cat config.log; false)
  - make -j6
script: "make -j6 test && make -j6 valtest"
cache:
  directories:
    - cache
